[package]
name = "calc"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "calc"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.25.0"
tokio = { version = "1.19.2", features = ["rt", "rt-multi-thread"] }
